spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
justedlev-service:
  auth:
    client:
        url: http://localhost:8080/api
  task-exec:
    register-tasks: true
    restore-tasks: true