spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
jaccount:
  client:
    url: http://localhost:8765/jaccount-service/api
jtask-exec:
  register-tasks: true
  restore-tasks: true