server:
  port: ${SERVER_PORT:8967}
  servlet:
    context-path: ${SERVICE_CONTEXT_PATH:/api}
spring:
  application:
    name: jtask-exec
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka